### ISSUE TITLE
关于运行python train_ATE.py 的问题

### ISSUE THREAD

**Issue by wll-best** [SCIR-MSA-Team/LC-ACSA#1]
您好，非常感谢您分享的代码！
我在运行train_ATE.py时遇到了一些问题，不知道这个sentence.txt是从哪里来的，希望您告知，非常感谢！
![image](https://user-images.githubusercontent.com/62608056/147314879-51f1da47-1b8a-4c99-9b1a-dbc55da71e35.png)

**Comment by loganzhang1** [comment]
您好，收到了您的邮件，两个文件的获取链接如下：
1.https://github.com/l294265421/AC-MIMLLN/blob/master/original_data/absa/ABSA_DevSplits/dataset/sentence_map.txt
2.https://github.com/NLPWM-WHU/SoftProto/blob/master/data/res14/train/sentence.txt

**Comment by wll-best** [comment]
您好，我看到您分享的链接了，非常感谢您的回复！
